name: Docs PR Preview

##########
# Do NOT call any scripts in the repo in this action.
# It is only safe if we run the Docker commands explicitly in the action.
##########

on:
  # This should be safe since the action doesn't do any build with the PR code
  # It would not be safe to run scripts from the PR code, so we use docker directly in this action
  pull_request_target:
    branches: [main]

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

jobs:
  doc-changes:
    runs-on: ubuntu-24.04
    permissions:
      pull-requests: write
    outputs:
      docs: ${{ steps.filter.outputs.docs }}

    steps:
      - name: Detect docs changes
        uses: dorny/paths-filter@v3
        id: filter
        with:
          filters: |
            docs:
              - 'docs/src/**'

      - name: No changes comment
        if: ${{ !contains(steps.filter.outputs.*, 'true') }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ## No docs changes detected for ${{ github.event.pull_request.head.sha }}

  doc-preview:
    needs: doc-changes
    runs-on: ubuntu-24.04
    if: ${{ contains(needs.doc-changes.outputs.*, 'true') }}
    permissions:
      id-token: write # Required to upload to AWS
      contents: read
      pull-requests: write

    steps:
      - name: Deploy preview comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ## Deploying docs previews for ${{ github.event.pull_request.head.sha }} (available for 14 days)

      ##########
      # Do NOT run any scripts sourced from the repo after this point. We have checked out the repo from a fork.
      # This has access to secrets. If we run any code provided by the repo at this point, it could be malicious.
      # https://securitylab.github.com/resources/github-actions-preventing-pwn-requests/
      ##########
      - uses: actions/checkout@v5
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - name: Sync docs to the salmon bucket
        id: sync-docs
        uses: deephaven/salmon-sync@v1
        with:
          source: docs/src
          destination: deephaven/barrage/pr-${{ github.event.number }}
          production: false
          temporary: true
          aws-role: ${{ vars.DOCS_AWS_ROLE }}
      - name: Update PR comment
        if: ${{ steps.sync-docs.outcome == 'success' }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          append: true
          message: |
            [Barrage](${{ vars.DOCS_PREVIEW_URL }}/barrage/pr-${{ github.event.number }}/docs/)

      - name: Update PR comment on fail
        if: ${{ failure() }}
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            ## :warning: Failed to deploy docs previews for ${{ github.event.pull_request.head.sha }}
            Please check the [logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for more details.
